server {
    listen 1414;
    server_name localhost;
    root /var/www/html;
    index indev.html index.html index.php ki14.html ki14.php;
    error_page 404 /err_pange/404.html;
    error_page 403 /err_pange/403.html;
    error_page 500 /err_pange/500.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        client_max_body_size 14000M;
    }

    location /admin {
        rewrite ^(.*)$ /register/admin_login.php redirect;
    }

    location ~ /\.ht {
        deny all;
    }
}